default_platform(:ios)

platform :ios do
  desc "Register devices"
  lane :reg do
    register_devices(devices: {
      "Temur 6S" => "58fa3c81bd6bc7f04ef850c2e18ce211b8dede88"
    })
    match(type: "development", force_for_new_devices: true)
    match(type: "adhoc", force_for_new_devices: true)
  end
end
