platform :ios, '11.0'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

PODS_PATH = '../../../Pods'
MODULES_PATH = PODS_PATH + '/Modules'
PACKAGES_PATH = PODS_PATH + '/Packages'
SERVICES_PATH = PODS_PATH + '/Services'
ONTOLOGY_PATH = PODS_PATH + '/Ontology'

target 'ProfitClub' do
  pod 'Nantes'
  pod 'Kingfisher'
  pod 'FittedSheets', '~> 2.2.3'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  # ontology
  pod 'ProfitClubModel', :path => ONTOLOGY_PATH + '/ProfitClubModel/ProfitClubModel.podspec'
  pod 'ProfitClubParse', :path => ONTOLOGY_PATH + '/ProfitClubParse/ProfitClubParse.podspec'
  
  # packages
  pod 'ErrorPresenter', :path => PACKAGES_PATH + '/ErrorPresenter/ErrorPresenter.podspec'
  pod 'ActivityPresenter', :path => PACKAGES_PATH + '/ActivityPresenter/ActivityPresenter.podspec'
  pod 'ConfirmationPresenter', :path => PACKAGES_PATH + '/ConfirmationPresenter/ConfirmationPresenter.podspec'
  pod 'MenuPresenter', :path => PACKAGES_PATH + '/MenuPresenter/MenuPresenter.podspec'
  
  # services
  pod 'PCAuthentication', :path => SERVICES_PATH + '/ProfitClub/PCAuthentication/PCAuthentication.podspec'
  pod 'PCUserService', :path => SERVICES_PATH + '/ProfitClub/PCUserService/PCUserService.podspec'
  pod 'PCOrganizationService', :path => SERVICES_PATH + '/ProfitClub/PCOrganizationService/PCOrganizationService.podspec'
  pod 'PCActionService', :path => SERVICES_PATH + '/ProfitClub/PCActionService/PCActionService.podspec'
  pod 'PCCommercialOfferService', :path => SERVICES_PATH + '/ProfitClub/PCCommercialOfferService/PCCommercialOfferService.podspec'
  pod 'PCSupplierService', :path => SERVICES_PATH + '/ProfitClub/PCSupplierService/PCSupplierService.podspec'
end

# Exclude all Package.swift from pods targets
post_install do |installer|
  puts("Excluding Package.swift from targets")
  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
