platform :ios, '11.0'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

PODS_PATH = '../../../Pods'
PACKAGES_PATH = PODS_PATH + '/Packages'
UTILS_PATH = PODS_PATH + '/Utils'

target 'ProfitClub' do
  pod 'Nantes'
  pod 'Kingfisher'
  pod 'FittedSheets', '~> 2.2.3'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  # ontology
  pod 'PCModel/Parse', :path => '../Model/PCModel/PCModel.podspec'
  
  # packages
  pod 'ErrorPresenter', :path => PACKAGES_PATH + '/ErrorPresenter/ErrorPresenter.podspec'
  pod 'ActivityPresenter', :path => PACKAGES_PATH + '/ActivityPresenter/ActivityPresenter.podspec'
  pod 'ConfirmationPresenter', :path => PACKAGES_PATH + '/ConfirmationPresenter/ConfirmationPresenter.podspec'
  pod 'MenuPresenter', :path => PACKAGES_PATH + '/MenuPresenter/MenuPresenter.podspec'
  pod 'Raise', :path => PACKAGES_PATH + '/Raise/Raise.podspec'
  
  # services
  pod 'PCAuthentication/Parse', :path => '../Services/PCAuthentication/PCAuthentication.podspec'
  pod 'PCUserService/Parse', :path => '../Services/PCUserService/PCUserService.podspec'
  pod 'PCOrganizationService', :path => '../Services/PCOrganizationService/PCOrganizationService.podspec'
  pod 'PCActionService', :path => '../Services/PCActionService/PCActionService.podspec'
  pod 'PCCommercialOfferService', :path => '../Services/PCCommercialOfferService/PCCommercialOfferService.podspec'
  pod 'PCSupplierService', :path => '../Services/PCSupplierService/PCSupplierService.podspec'

  # presentation
  pod 'PCOnboard', :path => '../Presentation/PCOnboard/PCOnboard.podspec'
  pod 'PCReview', :path => '../Presentation/PCReview/PCReview.podspec'
  pod 'PCAddRole', :path => '../Presentation/PCAddRole/PCAddRole.podspec'
  pod 'PCAdmin', :path => '../Presentation/PCAdmin/PCAdmin.podspec'
  pod 'PCSupplier', :path => '../Presentation/PCSupplier/PCSupplier.podspec'
  pod 'PCMember', :path => '../Presentation/PCMember/PCMember.podspec'
  pod 'PCOrganization', :path => '../Presentation/PCOrganization/PCOrganization.podspec'
  pod 'PCSupplierProfile', :path => '../Presentation/PCSupplierProfile/PCSupplierProfile.podspec'
  pod 'PCOrganizationProfile', :path => '../Presentation/PCOrganizationProfile/PCOrganizationProfile.podspec'
  pod 'PCMemberProfile', :path => '../Presentation/PCMemberProfile/PCMemberProfile.podspec'

  # persistence
  pod 'PCUserPersistence/Parse', :path => '../Persistence/PCUserPersistence/PCUserPersistence.podspec'

  # util
  pod 'PCFontProvider', :path => '../Util/PCFontProvider/PCFontProvider.podspec'
  pod 'BundleUtils', :path => UTILS_PATH + '/BundleUtils/BundleUtils.podspec'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
